| 2016-12-04 19:07:40 | object_manager.py | line: 80 | ERROR | put_object error | D:\MyCodes\GitRepos\OssAutoSync\testDirect\?????.txt___jb_tmp___ | [Errno 2] No such file or directory: 'D:\\MyCodes\\GitRepos\\OssAutoSync\\testDirect\\?????.txt___jb_tmp___'
| 2016-12-04 19:07:41 | object_manager.py | line: 130 | ERROR | rename_object error | test/?????.txt___jb_tmp___ | {'details': {'Key': 'test/?????.txt___jb_tmp___', 'RequestId': '5843F8FAE442C75C25C1BB20', 'HostId': 'private-stuff.oss-cn-shanghai.aliyuncs.com', 'Message': 'The specified key does not exist.', 'Code': 'NoSuchKey'}, 'status': 404}
