| 2016-11-16 17:42:42 | object_manager.py | line: 78 | ERROR | put_object error-- {'details': {}, 'status': 407}
| 2016-11-16 17:42:48 | object_manager.py | line: 78 | ERROR | put_object error-- {'details': {}, 'status': 407}
| 2016-11-16 17:42:48 | object_manager.py | line: 78 | ERROR | put_object error-- {'details': {}, 'status': 407}
| 2016-11-16 17:42:48 | object_manager.py | line: 78 | ERROR | put_object error-- {'details': {}, 'status': 407}
| 2016-11-16 17:49:34 | object_manager.py | line: 78 | ERROR | put_object error | D:\My Codes\MyRepo\OssAutoSync\testDirect\新建档.txt | {'status': 407, 'details': {}}
| 2016-11-16 17:50:34 | object_manager.py | line: 43 | ERROR | object_exists error | test/测试est/新建文件夹// | {'status': -2, 'details': "RequestError: HTTPConnectionPool(host='dl-proxy.neusoft.com', port=8080): Read timed out. (read timeout=60)"}
