| 2016-11-27 19:45:23 | object_manager.py | line: 133 | ERROR | rename_object error | test/≤‚ ‘test/sdfgg.py | {'status': 404, 'details': {'HostId': 'private-stuff.oss-cn-shanghai.aliyuncs.com', 'RequestId': '583AC753CCB80C214055225A', 'Key': 'test/≤‚ ‘test/sdfgg.py', 'Code': 'NoSuchKey', 'Message': 'The specified key does not exist.'}}
| 2016-11-27 19:45:23 | object_manager.py | line: 80 | ERROR | put_object error | D:\MyCodes\GitRepos\OssAutoSync\testDirect\≤‚ ‘test\sdfgg.py___jb_old___ | [Errno 2] No such file or directory: 'D:\\MyCodes\\GitRepos\\OssAutoSync\\testDirect\\≤‚ ‘test\\sdfgg.py___jb_old___'
| 2016-11-27 19:45:24 | object_manager.py | line: 133 | ERROR | rename_object error | test/≤‚ ‘test/sdfgg.py___jb_tmp___ | {'status': 404, 'details': {'HostId': 'private-stuff.oss-cn-shanghai.aliyuncs.com', 'RequestId': '583AC753E442C73D1D6A7A83', 'Key': 'test/≤‚ ‘test/sdfgg.py___jb_tmp___', 'Code': 'NoSuchKey', 'Message': 'The specified key does not exist.'}}
