| 2016-11-16 17:51:23 | object_manager.py | line: 78 | ERROR | put_object error | D:\My Codes\MyRepo\OssAutoSync\testDirect\新建文本文档 (4).txt | {'status': 407, 'details': {}}
| 2016-11-27 17:44:35 | main.py | line: 58 | ERROR | observer-init error | Failed to parse: domain:port
| 2016-11-27 17:46:04 | object_manager.py | line: 97 | ERROR | get_object error | test/aaa/bbb// | [Errno 2] No such file or directory: 'D:\\MyCodes\\GitRepos\\OssAutoSync\\testDirect\\aaa\\bbb\\\\'
| 2016-11-27 17:46:04 | object_manager.py | line: 97 | ERROR | get_object error | test/ccc// | [Errno 2] No such file or directory: 'D:\\MyCodes\\GitRepos\\OssAutoSync\\testDirect\\ccc\\\\'
| 2016-11-27 17:46:04 | object_manager.py | line: 97 | ERROR | get_object error | test/ccc/bbb// | [Errno 2] No such file or directory: 'D:\\MyCodes\\GitRepos\\OssAutoSync\\testDirect\\ccc\\bbb\\\\'
