| 2016-11-16 16:11:18 | object_manager.py | line: 77 | ERROR | put_object error-- {'details': {}, 'status': 407}
| 2016-11-16 16:11:22 | object_manager.py | line: 77 | ERROR | put_object error-- {'details': {}, 'status': 407}
