| 2016-11-13 19:34:00 | object_manager.py | line: 77 | ERROR | put_object error-- [Errno 2] No such file or directory: 'D:\\MyCodes\\GitRepos\\OssAutoSync\\testDirect\\≤‚ ‘test'
| 2016-11-13 19:34:00 | object_manager.py | line: 77 | ERROR | put_object error-- [Errno 2] No such file or directory: 'D:\\MyCodes\\GitRepos\\OssAutoSync\\testDirect\\≤‚ ‘test'
| 2016-11-13 19:52:38 | object_manager.py | line: 96 | ERROR | get_object error-- [Errno 2] No such file or directory: 'D:\\MyCodes\\GitRepos\\OssAutoSync\\testDirect\\aaa\\\\'
| 2016-11-13 19:52:38 | object_manager.py | line: 96 | ERROR | get_object error-- [Errno 2] No such file or directory: 'D:\\MyCodes\\GitRepos\\OssAutoSync\\testDirect\\aaa\\bbb\\\\'
| 2016-11-13 19:52:38 | object_manager.py | line: 96 | ERROR | get_object error-- [Errno 2] No such file or directory: 'D:\\MyCodes\\GitRepos\\OssAutoSync\\testDirect\\ccc\\\\'
