| 2016-11-13 19:52:38 | object_manager.py | line: 96 | ERROR | get_object error-- [Errno 2] No such file or directory: 'D:\\MyCodes\\GitRepos\\OssAutoSync\\testDirect\\ccc\\bbb\\\\'
| 2016-11-13 19:52:38 | object_manager.py | line: 96 | ERROR | get_object error-- [Errno 2] No such file or directory: 'D:\\MyCodes\\GitRepos\\OssAutoSync\\testDirect\\新建文件夹 (2)\\\\'
| 2016-11-13 19:52:39 | object_manager.py | line: 96 | ERROR | get_object error-- [Errno 2] No such file or directory: 'D:\\MyCodes\\GitRepos\\OssAutoSync\\testDirect\\新建文件夹 - 副本\\\\'
| 2016-11-13 19:52:39 | object_manager.py | line: 96 | ERROR | get_object error-- [Errno 2] No such file or directory: 'D:\\MyCodes\\GitRepos\\OssAutoSync\\testDirect\\测试est\\\\'
| 2016-11-13 19:52:39 | object_manager.py | line: 96 | ERROR | get_object error-- [Errno 2] No such file or directory: 'D:\\MyCodes\\GitRepos\\OssAutoSync\\testDirect\\测试est\\新建文件夹 (2)\\\\'
