2016-08-20 20:37:41,522 - main.objectManager - ERROR - get_object error-- {'details': {}, 'status': 404}
2016-08-20 20:37:57,581 - main.objectManager - ERROR - get_object error-- {'details': {}, 'status': 404}
2016-08-21 15:47:47,241 - main.objectManager - ERROR - put_object error-- [Errno 13] Permission denied: 'testDirect'
2016-08-21 15:47:47,242 - main.objectManager - ERROR - get_object error-- [Errno 13] Permission denied: 'testDirect'
2016-08-21 15:50:03,901 - main.objectManager - ERROR - put_object error-- [Errno 13] Permission denied: 'testDirect'
2016-08-21 15:51:42,371 - main.objectManager - ERROR - put_object error-- [Errno 2] No such file or directory: ''
2016-08-21 15:53:44,799 - main.objectManager - ERROR - put_object error-- [Errno 2] No such file or directory: '/testDirect'
2016-08-21 19:55:27,134 - main.objectManager - ERROR - put_object error-- Unicode-objects must be encoded before hashing
2016-08-21 19:55:27,134 - main.objectManager - ERROR - get_object error-- [Errno 2] No such file or directory: 'test/testPayLoad.html'
2016-08-21 20:00:06,770 - main.objectManager - ERROR - get_object error-- [Errno 2] No such file or directory: 'test/testPayLoad.html'
2016-09-03 22:29:18,842 - main - ERROR - observer-init error-- __init__() missing 1 required positional argument: 'bucket'
2016-09-03 22:30:39,352 - main.watchdogImpl - ERROR - rename error-- 'NoneType' object is not iterable
2016-09-03 22:31:25,849 - main.watchdogImpl - ERROR - rename error-- 'NoneType' object is not iterable
2016-09-03 22:34:05,497 - main.watchdogImpl - ERROR - rename error-- 'NoneType' object is not iterable
2016-09-03 22:34:42,319 - main.watchdogImpl - ERROR - rename error-- 'NoneType' object is not iterable
2016-09-03 22:35:03,026 - main.watchdogImpl - ERROR - rename error-- 'NoneType' object is not iterable
2016-09-03 22:37:46,622 - main.objectManager - ERROR - rename_object error-- 'latin-1' codec can't encode characters in position 20-23: ordinal not in range(256)
2016-09-03 22:43:57,390 - main.objectManager - ERROR - rename_object error-- 'latin-1' codec can't encode characters in position 20-22: ordinal not in range(256)
2016-09-03 22:47:27,352 - main.objectManager - ERROR - rename_object error-- 'latin-1' codec can't encode characters in position 20-21: ordinal not in range(256)
2016-09-03 22:53:34,822 - main.objectManager - ERROR - rename_object error-- 'latin-1' codec can't encode characters in position 20-21: ordinal not in range(256)
2016-09-03 22:54:15,737 - main.objectManager - ERROR - rename_object error-- 'latin-1' codec can't encode characters in position 20-21: ordinal not in range(256)
2016-09-04 19:30:36,522 - main.watchdogImpl - ERROR - rename error-- 'str' object has no attribute 'decode'
2016-09-04 19:31:36,340 - main.watchdogImpl - ERROR - rename error-- 'str' object has no attribute 'decode'
2016-09-04 19:32:01,033 - main.watchdogImpl - ERROR - rename error-- 'str' object has no attribute 'decode'
2016-09-04 19:37:20,559 - main.objectManager - ERROR - rename_object error-- 'latin-1' codec can't encode characters in position 20-21: ordinal not in range(256)
2016-09-04 19:41:52,301 - main.objectManager - ERROR - rename_object error-- 'latin-1' codec can't encode characters in position 20-21: ordinal not in range(256)
2016-09-04 20:57:52,347 - main.objectManager - ERROR - rename_object error-- Can't convert 'bytes' object to str implicitly
2016-09-04 21:12:47,591 - main.objectManager - ERROR - rename_object error-- Can't convert 'bytes' object to str implicitly
2016-09-04 21:13:08,469 - main.objectManager - ERROR - rename_object error-- Can't convert 'bytes' object to str implicitly
2016-09-04 21:17:35,416 - main.objectManager - ERROR - rename_object error-- Can't convert 'bytes' object to str implicitly
2016-09-04 21:54:22,678 - main.objectManager - ERROR - rename_object error-- 'latin-1' codec can't encode character '\u65b0' in position 20: ordinal not in range(256)
2016-09-04 21:54:59,572 - main.objectManager - ERROR - rename_object error-- 'latin-1' codec can't encode character '\u65b0' in position 20: ordinal not in range(256)
2016-09-04 21:58:35,018 - main.objectManager - ERROR - rename_object error-- 'latin-1' codec can't encode character '\u65b0' in position 20: ordinal not in range(256)
2016-09-04 22:07:11,353 - main.objectManager - ERROR - rename_object error-- 'latin-1' codec can't encode character '\u65b0' in position 20: ordinal not in range(256)
2016-09-04 22:07:22,060 - main.objectManager - ERROR - rename_object error-- 'latin-1' codec can't encode character '\u65b0' in position 20: ordinal not in range(256)
2016-09-04 22:08:37,770 - main.objectManager - ERROR - rename_object error-- 'latin-1' codec can't encode character '\u65b0' in position 20: ordinal not in range(256)
2016-09-04 22:20:20,879 - main.objectManager - ERROR - rename_object error-- 'latin-1' codec can't encode character '\u65b0' in position 20: ordinal not in range(256)
2016-09-13 15:11:50,559 - main.objectManager - ERROR - rename_object error-- 'latin-1' codec can't encode character '\u65b0' in position 20: ordinal not in range(256)
2016-09-13 15:12:31,228 - main.objectManager - ERROR - rename_object error-- 'latin-1' codec can't encode character '\u65b0' in position 20: ordinal not in range(256)
2016-09-13 16:07:18,805 - main.objectManager - ERROR - rename_object error-- Can't convert 'bytes' object to str implicitly
2016-09-14 14:51:39,188 - main.objectManager - ERROR - put_object error-- [Errno 13] Permission denied: 'D:\\My Codes\\MyRepo\\OssAutoSynch\\testDirect\\新建文件夹'
2016-09-14 15:05:41,112 - main.objectManager - ERROR - put_object error-- [Errno 13] Permission denied: 'D:\\My Codes\\MyRepo\\OssAutoSynch\\testDirect\\新建文件夹'
2016-09-14 15:30:52,404 - main.objectManager - ERROR - put_object error-- [Errno 13] Permission denied: 'D:\\My Codes\\MyRepo\\OssAutoSynch\\testDirect\\新建文件夹'
2016-09-14 15:31:17,866 - main.objectManager - ERROR - put_object error-- [Errno 13] Permission denied: 'D:\\My Codes\\MyRepo\\OssAutoSynch\\testDirect\\新建文件夹 (3)'
2016-09-14 15:33:41,386 - main.objectManager - ERROR - put_object error-- [Errno 13] Permission denied: 'D:\\My Codes\\MyRepo\\OssAutoSynch\\testDirect\\.idea'
2016-09-14 16:38:47,192 - main.objectManager - ERROR - put_object error-- [Errno 13] Permission denied: 'D:\\My Codes\\MyRepo\\OssAutoSynch\\testDirect\\新建文件'
2016-09-14 16:39:40,041 - main.objectManager - ERROR - put_object error-- [Errno 13] Permission denied: 'D:\\My Codes\\MyRepo\\OssAutoSynch\\testDirect\\测试tesd'
2016-09-14 16:44:32,932 - main.objectManager - ERROR - put_object error-- [Errno 13] Permission denied: 'D:\\My Codes\\MyRepo\\OssAutoSynch\\testDirect\\测试test'
2016-09-14 16:50:02,557 - main.objectManager - ERROR - put_object error-- [Errno 13] Permission denied: 'D:\\My Codes\\MyRepo\\OssAutoSynch\\testDirect\\测试test\\新建文件夹'
2016-09-14 16:50:43,088 - main.objectManager - ERROR - put_object error-- [Errno 13] Permission denied: 'D:\\My Codes\\MyRepo\\OssAutoSynch\\testDirect\\测试test\\新建文件夹 (2)'
2016-09-24 22:01:02,250 - main.objectManager - ERROR - put_object error-- [Errno 13] Permission denied: 'D:\\MyCodes\\GitRepos\\OssAutoSynch\\testDirect\\新建文件夹'
2016-09-24 22:05:07,969 - main.objectManager - ERROR - put_object error-- [Errno 13] Permission denied: 'D:\\MyCodes\\GitRepos\\OssAutoSynch\\testDirect\\新建文件夹 (3)'
2016-09-24 22:05:34,948 - main.objectManager - ERROR - put_object error-- [Errno 13] Permission denied: 'D:\\MyCodes\\GitRepos\\OssAutoSynch\\testDirect\\新建文件夹 (4)'
2016-09-24 22:08:30,363 - main.objectManager - ERROR - put_object error-- [Errno 13] Permission denied: 'D:\\MyCodes\\GitRepos\\OssAutoSynch\\testDirect\\新建文件夹 (5)'
2016-11-06 14:21:08,536 - main - ERROR - observer-init error-- remote_path does not belong to this root
2016-11-06 14:22:03,742 - main - ERROR - observer-init error-- remote_path does not belong to this root
2016-11-06 14:29:35,234 - main.objectManager - ERROR - get_object error-- [Errno 2] No such file or directory: 'D:\\MyCodes\\GitRepos\\OssAutoSynch\\testDirect\\'
2016-11-06 14:40:48,268 - main.objectManager - ERROR - get_object error-- [Errno 2] No such file or directory: 'D:\\MyCodes\\GitRepos\\OssAutoSynch\\testDirect\\新建文件夹 (2)\\'
2016-11-06 15:05:21,935 - main.objectManager - ERROR - get_object error-- [Errno 2] No such file or directory: 'D:\\MyCodes\\GitRepos\\OssAutoSynch\\testDirect\\测试test\\新jk和g .txt'
2016-11-06 15:05:21,936 - main.objectManager - ERROR - get_object error-- [Errno 2] No such file or directory: 'D:\\MyCodes\\GitRepos\\OssAutoSynch\\testDirect\\测试test\\新建文件夹 (2)\\新建 Microsoft PowerPoint 演示文稿.pptx'
2016-11-06 15:05:21,936 - main.objectManager - ERROR - get_object error-- [Errno 2] No such file or directory: 'D:\\MyCodes\\GitRepos\\OssAutoSynch\\testDirect\\测试test\\新建文件夹\\新建文本文档.txt'
2016-11-06 15:05:21,937 - main.objectManager - ERROR - get_object error-- [Errno 2] No such file or directory: 'D:\\MyCodes\\GitRepos\\OssAutoSynch\\testDirect\\测试test\\新建文本文档 (2.txt'
2016-11-06 15:05:21,938 - main - ERROR - observer-init error-- bad escape (end of pattern) at position 44
2016-11-06 17:03:41,663 - main.syncSocket - INFO - file deleted:D:\MyCodes\GitRepos\OssAutoSynch\testDirect\测试
2016-11-06 17:04:33,800 - main.syncSocket - INFO - file created:D:\MyCodes\GitRepos\OssAutoSynch\testDirect\aaa
2016-11-06 17:04:40,139 - main.syncSocket - INFO - file created:D:\MyCodes\GitRepos\OssAutoSynch\testDirect\aaa\bbb
2016-11-06 17:04:51,905 - main.syncSocket - INFO - file created:D:\MyCodes\GitRepos\OssAutoSynch\testDirect\ccc
2016-11-06 17:04:53,004 - main.syncSocket - INFO - file created:D:\MyCodes\GitRepos\OssAutoSynch\testDirect\ccc\bbb
2016-11-06 17:04:53,714 - main.syncSocket - INFO - file created:D:\MyCodes\GitRepos\OssAutoSynch\testDirect\ccc\bbb
2016-11-06 17:28:31,704 - main.syncSocket - INFO - file created:D:\MyCodes\GitRepos\OssAutoSynch\testDirect\测试test
2016-11-06 17:28:32,790 - main.syncSocket - INFO - file created:D:\MyCodes\GitRepos\OssAutoSynch\testDirect\测试test\新建文件夹
2016-11-06 17:28:33,052 - main.syncSocket - INFO - file created:D:\MyCodes\GitRepos\OssAutoSynch\testDirect\测试test\新建文件夹 (2)
2016-11-06 17:28:33,494 - main.syncSocket - INFO - file created:D:\MyCodes\GitRepos\OssAutoSynch\testDirect\测试test\新jk和g .txt
2016-11-06 17:28:33,851 - main.syncSocket - INFO - file created:D:\MyCodes\GitRepos\OssAutoSynch\testDirect\测试test\新建文本文档 (2.txt
2016-11-06 17:28:34,300 - main.syncSocket - INFO - file created:D:\MyCodes\GitRepos\OssAutoSynch\testDirect\测试test\新建文件夹\新建文本文档.txt
2016-11-06 17:28:34,609 - main.syncSocket - INFO - file created:D:\MyCodes\GitRepos\OssAutoSynch\testDirect\测试test\新建文件夹 (2)\新建 Microsoft PowerPoint 演示文稿.pptx
2016-11-06 17:28:34,962 - main.syncSocket - INFO - file created:D:\MyCodes\GitRepos\OssAutoSynch\testDirect\测试test\新jk和g .txt
2016-11-06 17:28:35,421 - main.syncSocket - INFO - file created:D:\MyCodes\GitRepos\OssAutoSynch\testDirect\测试test\新建文件夹 (2)
2016-11-06 17:28:35,753 - main.syncSocket - INFO - file created:D:\MyCodes\GitRepos\OssAutoSynch\testDirect\测试test\新建文件夹 (2)\新建 Microsoft PowerPoint 演示文稿.pptx
2016-11-06 17:28:36,243 - main.syncSocket - INFO - file created:D:\MyCodes\GitRepos\OssAutoSynch\testDirect\测试test\新建文件夹
2016-11-06 17:28:36,576 - main.syncSocket - INFO - file created:D:\MyCodes\GitRepos\OssAutoSynch\testDirect\测试test\新建文件夹\新建文本文档.txt
2016-11-06 17:28:37,013 - main.syncSocket - INFO - file created:D:\MyCodes\GitRepos\OssAutoSynch\testDirect\测试test\新建文本文档 (2.txt
2016-11-06 17:33:21,859 - main - ERROR - observer-init error-- [WinError 183] 当文件已存在时，无法创建该文件。: 'D:\\MyCodes\\GitRepos\\OssAutoSynch\\.git\\'
2016-11-06 17:33:45,102 - main - ERROR - observer-init error-- [WinError 183] 当文件已存在时，无法创建该文件。: 'D:\\MyCodes\\GitRepos\\OssAutoSynch\\.git\\'
2016-11-06 17:41:05,726 - main.objectManager - ERROR - get_object error-- [Errno 2] No such file or directory: 'D:\\MyCodes\\Coursera\\'
2016-11-06 17:41:05,727 - main - ERROR - observer-init error-- bad escape (end of pattern) at position 20
2016-11-06 17:43:04,341 - main - ERROR - observer-init error-- bad escape (end of pattern) at position 20
2016-11-06 17:43:50,275 - main - ERROR - observer-init error-- bad escape (end of pattern) at position 20
2016-11-06 17:47:15,559 - main - ERROR - observer-init error-- bad escape (end of pattern) at position 20
2016-11-06 17:57:17,384 - main - ERROR - observer-init error-- bad escape (end of pattern) at position 20
2016-11-06 18:00:39,924 - main - ERROR - observer-init error-- [WinError 183] 当文件已存在时，无法创建该文件。: 'D:\\MyCodes\\Coursera\\AngularJS\\conFusion\\.DS_Store\\'
